### ISSUE TITLE
Not working in Swift

### ISSUE THREAD

**Issue by salmankhann** [rtecson/RTAlertView#2]
Hi, I was trying to use your library and it does not work in swift. After importing the library into my project and the library import in the Bridging-header, swift recognises the init method but does not translate the last parameter otherButtonTitles into its method signature. If we try to add that parameter, it throws a compilation error. Using the library without the last parameter, compiles, but on runtime gives this error 

-[RTAlertView initWithTitle:message:delegate:cancelButtonTitle:]: unrecognized selector sent to instance

How can we fix this? Thanks a lot!

**Comment by rtecson** [comment]
Hi chemjournal. Thanks for reporting this. I haven't tried running this in Swift yet, but I will take a look and let you know what I find. Thanks!

**Comment by salmankhann** [comment]
For some reason it does not recognize the last variadic parameter. As a
workaround, I just created a new initializer in RTAlertview without the
last parameter and called your default initializer passing nil for the
otherbuttontitles variadic parameter and it works fine. But that's just a
workaround for now. How can we fix this ?

**Comment by rtecson** [comment]
Apparently, C-style variadics are not supported in Swift as they are not compatible with Swift-style variadics (see https://devforums.apple.com/message/983462#983462).

I found a solution here (http://stackoverflow.com/questions/24195796/how-do-you-call-an-objective-c-variadic-method-from-swift). In summary, to continue supporting variable number of otherButtonTitle strings, we'll need to create a new initializer that uses the the va_list version instead of the C-style variadic method signature. This va_list version may be called from Swift. (The article also suggests a method where native Swift-style variadics may be supported also.)

chemjournal, in your case, if you do not require the use of variadic parameters, your workaround/solution should work. There is also the addButtonWithTitle: that you can call to add other button titles even if this capability were removed in your new initializer.

I will implement and test the solution outlined in the article above, and will update the RTAlertView library once I've tested it. Thanks for bringing this to my attention!

**Comment by rtecson** [comment]
Hi chemjournal,

I've updated RTAlertView and provided a non-variadic initializer. This may bridged successfully from Swift. This initializer will only take one otherButtonTitle, but you can add additional ones using the method -addButtonWithTitle:.

I've updated the README file and added a section for Swift bridging. Hope this helps.

**Comment by salmankhann** [comment]
Awesome work Roland! I'm facing another issue with RBBAnimation
dependency where
iOS complains that the precompiled header is too old. Are you facing the
same issue?

**Comment by rtecson** [comment]
I don't see that in my use of RBBAnimation. Have you tried performing a clean and clean build folder?
